<body class="single" dir="LTR">
    <div class="mt2"><span class="mt2">The Good News According to </span></div>
    <div class="mt"><span class="mt">John </span></div>
    <div class="b"></div>
    <div class="b"></div>
    <div class="m">
        <div class="c-drop">1</div> 
        <div id="1a" class="txs seltxt">
                <span class="v">1</span>
            <span class="vsp">&nbsp;</span>
            In the beginning was the Word,
        </div> 
        <div id="1b" class="txs seltxt">and the Word was with God,</div> 
        <div id="1c" class="txs seltxt">and the Word was God. </div>
        <span id="bookmarks1"></span> 
        
        <div id="2" class="txs seltxt">
                <span class="v">2</span>
            <span class="vsp">&nbsp;</span>
            The same was in the beginning with God. 
        </div><span id="bookmarks2"></span> 
        
        <div id="3a" class="txs seltxt">
                <span class="v">3</span>
            <span class="vsp">&nbsp;</span>
            All things were made through him.
        </div> 
        <div id="3b" class="txs seltxt">Without him,</div> 
        <div id="3c" class="txs seltxt">nothing was made that has been made. </div>
        <span id="bookmarks3"></span> 
        
        <div id="4a" class="txs seltxt">
            <span class="v">4</span>
            <span class="vsp">&nbsp;</span>
            In him was life,
        </div> 
        <div id="4b" class="txs seltxt">and the life was the light of men. </div>
        <span id="bookmarks4"></span> 
        
        <div id="5a" class="txs seltxt">
            <span class="v">5</span>
            <span class="vsp">&nbsp;</span>
            The light shines in the darkness,
        </div> 
        <div id="5b" class="txs seltxt">and the darkness hasn’t overcome<span class="footnote"><sup>a</sup></span> it. </div>
        <span id="bookmarks5"></span>
    </div>
    <span id="bookmarks5"></span>
    <div class="p"><div id="6a" class="txs seltxt"><span class="v">6</span><span class="vsp">&nbsp;</span>There came a man sent from God,</div> <div id="6b" class="txs seltxt">whose name was John. </div><span id="bookmarks6"></span> <div id="7a" class="txs seltxt"><span class="v">7</span><span class="vsp">&nbsp;</span>The same came as a witness,</div> <div id="7b" class="txs seltxt">that he might testify about the light,</div> <div id="7c" class="txs seltxt">that all might believe through him. </div><span id="bookmarks7"></span> <div id="8a" class="txs seltxt"><span class="v">8</span><span class="vsp">&nbsp;</span>He was not the light,</div> <div id="8b" class="txs seltxt">but was sent that he might testify about the light. </div><span id="bookmarks8"></span> <div id="9" class="txs seltxt"><span class="v">9</span><span class="vsp">&nbsp;</span>The true light that enlightens everyone was coming into the world. </div><span id="bookmarks9"></span></div><span id="bookmarks9"></span>
    <div class="p"><div id="10a" class="txs seltxt"><span class="v">10</span><span class="vsp">&nbsp;</span>He was in the world,</div> <div id="10b" class="txs seltxt">and the world was made through him,</div> <div id="10c" class="txs seltxt">and the world didn’t recognize him. </div><span id="bookmarks10"></span> <div id="11a" class="txs seltxt"><span class="v">11</span><span class="vsp">&nbsp;</span>He came to his own,</div> <div id="11b" class="txs seltxt">and those who were his own didn’t receive him. </div><span id="bookmarks11"></span> <div id="12a" class="txs seltxt"><span class="v">12</span><span class="vsp">&nbsp;</span>But as many as received him,</div> <div id="12b" class="txs seltxt">to them he gave the right to become God’s children,</div> <div id="12c" class="txs seltxt">to those who believe in his name: </div><span id="bookmarks12"></span> <div id="13a" class="txs seltxt"><span class="v">13</span><span class="vsp">&nbsp;</span>who were born,</div> <div id="13b" class="txs seltxt">not of blood,</div> <div id="13c" class="txs seltxt">nor of the will of the flesh,</div> <div id="13d" class="txs seltxt">nor of the will of man,</div> <div id="13e" class="txs seltxt">but of God. </div><span id="bookmarks13"></span></div><span id="bookmarks13"></span>
    <div class="p"><div id="14a" class="txs seltxt"><span class="v">14</span><span class="vsp">&nbsp;</span>The Word became flesh and lived among us.</div> <div id="14b" class="txs seltxt">We saw his glory,</div> <div id="14c" class="txs seltxt">such glory as of the only born<span class="footnote"><sup>b</sup></span> Son of the Father,</div> <div id="14d" class="txs seltxt">full of grace and truth. </div><span id="bookmarks14"></span> <div id="15a" class="txs seltxt"><span class="v">15</span><span class="vsp">&nbsp;</span>John testified about him.</div> <div id="15b" class="txs seltxt">He cried out,</div> <div id="15c" class="txs seltxt">saying,</div> <div id="15d" class="txs seltxt">“This was he of whom I said,</div> <div id="15e" class="txs seltxt">‘He who comes after me has surpassed me,</div> <div id="15f" class="txs seltxt">for he was before me.’” </div><span id="bookmarks15"></span> <div id="16" class="txs seltxt"><span class="v">16</span><span class="vsp">&nbsp;</span>From his fullness we all received grace upon grace. </div><span id="bookmarks16"></span> <div id="17a" class="txs seltxt"><span class="v">17</span><span class="vsp">&nbsp;</span>For the law was given through Moses.</div> <div id="17b" class="txs seltxt">Grace and truth were realized through <span class="glossary">Jesus</span> Christ.<span class="footnote"><sup>c</sup></span> </div><span id="bookmarks17"></span> <div id="18a" class="txs seltxt"><span class="v">18</span><span class="vsp">&nbsp;</span>No one has seen God at any time.</div> <div id="18b" class="txs seltxt">The only born<span class="footnote"><sup>d</sup></span> Son,<span class="footnote"><sup>e</sup></span></div> <div id="18c" class="txs seltxt">who is in the bosom of the Father,</div> <div id="18d" class="txs seltxt">has declared him. </div><span id="bookmarks18"></span></div><span id="bookmarks18"></span>
    <div class="p"><div id="19a" class="txs seltxt"><span class="v">19</span><span class="vsp">&nbsp;</span>This is John’s testimony,</div> <div id="19b" class="txs seltxt">when the Jews sent priests and Levites from Jerusalem to ask him,</div> <div id="19c" class="txs seltxt">“Who are you?” </div><span id="bookmarks19"></span></div><span id="bookmarks19"></span>
    <div class="p"><div id="20a" class="txs seltxt"><span class="v">20</span><span class="vsp">&nbsp;</span>He declared,</div> <div id="20b" class="txs seltxt">and didn’t deny,</div> <div id="20c" class="txs seltxt">but he declared,</div> <div id="20d" class="txs seltxt">“I am not the Christ.” </div><span id="bookmarks20"></span></div><span id="bookmarks20"></span>
    <div class="p"><div id="21a" class="txs seltxt"><span class="v">21</span><span class="vsp">&nbsp;</span>They asked him,</div> <div id="21b" class="txs seltxt">“What then?</div> <div id="21c" class="txs seltxt">Are you Elijah?” </div></div>
    <div class="p"><div id="21d" class="txs seltxt">He said,</div> <div id="21e" class="txs seltxt">“I am not.” </div></div>
    <div class="p"><div id="21f" class="txs seltxt">“Are you the prophet?” </div></div>
    <div class="p"><div id="21g" class="txs seltxt">He answered,</div> <div id="21h" class="txs seltxt">“No.” </div><span id="bookmarks21"></span></div><span id="bookmarks21"></span>
    <div class="p"><div id="22a" class="txs seltxt"><span class="v">22</span><span class="vsp">&nbsp;</span>They said therefore to him,</div> <div id="22b" class="txs seltxt">“Who are you?</div> <div id="22c" class="txs seltxt">Give us an answer to take back to those who sent us.</div> <div id="22d" class="txs seltxt">What do you say about yourself?” </div><span id="bookmarks22"></span></div><span id="bookmarks22"></span>
    <div class="p"><div id="23a" class="txs seltxt"><span class="v">23</span><span class="vsp">&nbsp;</span>He said,</div> <div id="23b" class="txs seltxt">“I am the voice of one crying in the wilderness,</div> <div id="23c" class="txs seltxt">‘Make straight the way of the Lord,’<span class="footnote"><sup>f</sup></span></div> <div id="23d" class="txs seltxt">as Isaiah the prophet said.” </div><span id="bookmarks23"></span></div><span id="bookmarks23"></span>
    <div class="p"><div id="24" class="txs seltxt"><span class="v">24</span><span class="vsp">&nbsp;</span>The ones who had been sent were from the Pharisees. </div><span id="bookmarks24"></span> <div id="25a" class="txs seltxt"><span class="v">25</span><span class="vsp">&nbsp;</span>They asked him,</div> <div id="25b" class="txs seltxt">“Why then do you <span class="glossary">baptize</span> if you are not the Christ,</div> <div id="25c" class="txs seltxt">nor Elijah,</div> <div id="25d" class="txs seltxt">nor the prophet?” </div><span id="bookmarks25"></span></div><span id="bookmarks25"></span>
    <div class="p"><div id="26a" class="txs seltxt"><span class="v">26</span><span class="vsp">&nbsp;</span>John answered them,</div> <div id="26b" class="txs seltxt">“I <span class="glossary">baptize</span> in water,</div> <div id="26c" class="txs seltxt">but among you stands one whom you don’t know. </div><span id="bookmarks26"></span> <div id="27a" class="txs seltxt"><span class="v">27</span><span class="vsp">&nbsp;</span>He is the one who comes after me,</div> <div id="27b" class="txs seltxt">who is preferred before me,</div> <div id="27c" class="txs seltxt">whose sandal strap I’m not worthy to loosen.” </div><span id="bookmarks27"></span> <div id="28a" class="txs seltxt"><span class="v">28</span><span class="vsp">&nbsp;</span>These things were done in Bethany beyond the Jordan,</div> <div id="28b" class="txs seltxt">where John was baptizing. </div><span id="bookmarks28"></span></div><span id="bookmarks28"></span>
    <div class="p"><div id="29a" class="txs seltxt"><span class="v">29</span><span class="vsp">&nbsp;</span>The next day,</div> <div id="29b" class="txs seltxt">he saw <span class="glossary">Jesus</span> coming to him,</div> <div id="29c" class="txs seltxt">and said,</div> <div id="29d" class="txs seltxt">“<span class="glossary">Behold</span>,<span class="footnote"><sup>g</sup></span></div> <div id="29e" class="txs seltxt">the Lamb of God,</div> <div id="29f" class="txs seltxt">who takes away the sin of the world! </div><span id="bookmarks29"></span> <div id="30a" class="txs seltxt"><span class="v">30</span><span class="vsp">&nbsp;</span>This is he of whom I said,</div> <div id="30b" class="txs seltxt">‘After me comes a man who is preferred before me,</div> <div id="30c" class="txs seltxt">for he was before me.’ </div><span id="bookmarks30"></span> <div id="31a" class="txs seltxt"><span class="v">31</span><span class="vsp">&nbsp;</span>I didn’t know him,</div> <div id="31b" class="txs seltxt">but for this reason I came baptizing in water,</div> <div id="31c" class="txs seltxt">that he would be revealed to Israel.” </div><span id="bookmarks31"></span> <div id="32a" class="txs seltxt"><span class="v">32</span><span class="vsp">&nbsp;</span>John testified,</div> <div id="32b" class="txs seltxt">saying,</div> <div id="32c" class="txs seltxt">“I have seen the <span class="glossary">Spirit</span> descending like a dove out of heaven,</div> <div id="32d" class="txs seltxt">and it remained on him. </div><span id="bookmarks32"></span> <div id="33a" class="txs seltxt"><span class="v">33</span><span class="vsp">&nbsp;</span>I didn’t recognize him,</div> <div id="33b" class="txs seltxt">but he who sent me to <span class="glossary">baptize</span> in water said to me,</div> <div id="33c" class="txs seltxt">‘On whomever you will see the <span class="glossary">Spirit</span> descending and remaining on him is he who baptizes in the Holy <span class="glossary">Spirit</span>.’ </div><span id="bookmarks33"></span> <div id="34" class="txs seltxt"><span class="v">34</span><span class="vsp">&nbsp;</span>I have seen and have testified that this is the Son of God.” </div><span id="bookmarks34"></span></div><span id="bookmarks34"></span>
    <div class="p"><div id="35a" class="txs seltxt"><span class="v">35</span><span class="vsp">&nbsp;</span>Again,</div> <div id="35b" class="txs seltxt">the next day,</div> <div id="35c" class="txs seltxt">John was standing with two of his disciples, </div><span id="bookmarks35"></span> <div id="36a" class="txs seltxt"><span class="v">36</span><span class="vsp">&nbsp;</span>and he looked at <span class="glossary">Jesus</span> as he walked,</div> <div id="36b" class="txs seltxt">and said,</div> <div id="36c" class="txs seltxt">“<span class="glossary">Behold</span>,</div> <div id="36d" class="txs seltxt">the Lamb of God!” </div><span id="bookmarks36"></span> <div id="37a" class="txs seltxt"><span class="v">37</span><span class="vsp">&nbsp;</span>The two disciples heard him speak,</div> <div id="37b" class="txs seltxt">and they followed <span class="glossary">Jesus</span>. </div><span id="bookmarks37"></span> <div id="38a" class="txs seltxt"><span class="v">38</span><span class="vsp">&nbsp;</span><span class="glossary">Jesus</span> turned and saw them following,</div> <div id="38b" class="txs seltxt">and said to them,</div> <div id="38c" class="txs seltxt"><span class="wj">“What are you looking for?”</span> </div></div>
    <div class="p"><div id="38d" class="txs seltxt">They said to him,</div> <div id="38e" class="txs seltxt">“<span class="glossary">Rabbi</span>” (which is to say,</div> <div id="38f" class="txs seltxt">being interpreted,</div> <div id="38g" class="txs seltxt">Teacher),</div> <div id="38h" class="txs seltxt">“where are you staying?” </div><span id="bookmarks38"></span></div><span id="bookmarks38"></span>
    <div class="p"><div id="39a" class="txs seltxt"><span class="v">39</span><span class="vsp">&nbsp;</span>He said to them,</div> <div id="39b" class="txs seltxt"><span class="wj">“Come and see.”</span> </div></div>
    <div class="p"><div id="39c" class="txs seltxt">They came and saw where he was staying,</div> <div id="39d" class="txs seltxt">and they stayed with him that day.</div> <div id="39e" class="txs seltxt">It was about the tenth hour.<span class="footnote"><sup>h</sup></span> </div><span id="bookmarks39"></span> <div id="40a" class="txs seltxt"><span class="v">40</span><span class="vsp">&nbsp;</span>One of the two who heard John and followed him was Andrew,</div> <div id="40b" class="txs seltxt">Simon Peter’s brother. </div><span id="bookmarks40"></span> <div id="41a" class="txs seltxt"><span class="v">41</span><span class="vsp">&nbsp;</span>He first found his own brother,</div> <div id="41b" class="txs seltxt">Simon,</div> <div id="41c" class="txs seltxt">and said to him,</div> <div id="41d" class="txs seltxt">“We have found the Messiah!”</div> <div id="41e" class="txs seltxt">(which is,</div> <div id="41f" class="txs seltxt">being interpreted,</div> <div id="41g" class="txs seltxt">Christ<span class="footnote"><sup>i</sup></span>). </div><span id="bookmarks41"></span> <div id="42a" class="txs seltxt"><span class="v">42</span><span class="vsp">&nbsp;</span>He brought him to <span class="glossary">Jesus</span>.</div> <div id="42b" class="txs seltxt"><span class="glossary">Jesus</span> looked at him and said,</div> <div id="42c" class="txs seltxt"><span class="wj">“You are Simon the son of Jonah.</span></div> <div id="42d" class="txs seltxt"><span class="wj">You shall be called Cephas”</span> (which is by interpretation,</div> <div id="42e" class="txs seltxt">Peter).<span class="footnote"><sup>j</sup></span> </div><span id="bookmarks42"></span></div><span id="bookmarks42"></span>
    <div class="p"><div id="43a" class="txs seltxt"><span class="v">43</span><span class="vsp">&nbsp;</span>On the next day,</div> <div id="43b" class="txs seltxt">he was determined to go out into Galilee,</div> <div id="43c" class="txs seltxt">and he found Philip.</div> <div id="43d" class="txs seltxt"><span class="glossary">Jesus</span> said to him,</div> <div id="43e" class="txs seltxt"><span class="wj">“Follow me.”</span> </div><span id="bookmarks43"></span> <div id="44a" class="txs seltxt"><span class="v">44</span><span class="vsp">&nbsp;</span>Now Philip was from Bethsaida,</div> <div id="44b" class="txs seltxt">the city of Andrew and Peter. </div><span id="bookmarks44"></span> <div id="45a" class="txs seltxt"><span class="v">45</span><span class="vsp">&nbsp;</span>Philip found Nathanael,</div> <div id="45b" class="txs seltxt">and said to him,</div> <div id="45c" class="txs seltxt">“We have found him of whom Moses in the law and also the prophets,</div> <div id="45d" class="txs seltxt">wrote:</div> <div id="45e" class="txs seltxt"><span class="glossary">Jesus</span> of Nazareth,</div> <div id="45f" class="txs seltxt">the son of Joseph.” </div><span id="bookmarks45"></span></div><span id="bookmarks45"></span>
    <div class="p"><div id="46a" class="txs seltxt"><span class="v">46</span><span class="vsp">&nbsp;</span>Nathanael said to him,</div> <div id="46b" class="txs seltxt">“Can any good thing come out of Nazareth?” </div></div>
    <div class="p"><div id="46c" class="txs seltxt">Philip said to him,</div> <div id="46d" class="txs seltxt">“Come and see.” </div><span id="bookmarks46"></span></div><span id="bookmarks46"></span>
    <div class="p"><div id="47a" class="txs seltxt"><span class="v">47</span><span class="vsp">&nbsp;</span><span class="glossary">Jesus</span> saw Nathanael coming to him,</div> <div id="47b" class="txs seltxt">and said about him,</div> <div id="47c" class="txs seltxt"><span class="wj">“<span class="glossary">Behold</span>,</span></div> <div id="47d" class="txs seltxt">an Israelite indeed,</div> <div id="47e" class="txs seltxt">in whom is no deceit!” </div><span id="bookmarks47"></span></div><span id="bookmarks47"></span>
    <div class="p"><div id="48a" class="txs seltxt"><span class="v">48</span><span class="vsp">&nbsp;</span>Nathanael said to him,</div> <div id="48b" class="txs seltxt">“How do you know me?” </div></div>
    <div class="p"><div id="48c" class="txs seltxt"><span class="glossary">Jesus</span> answered him,</div> <div id="48d" class="txs seltxt"><span class="wj">“Before Philip called you,</span></div> <div id="48e" class="txs seltxt"><span class="wj">when you were under the fig tree,</span></div> <div id="48f" class="txs seltxt"><span class="wj">I saw you.”</span> </div><span id="bookmarks48"></span></div><span id="bookmarks48"></span>
    <div class="p"><div id="49a" class="txs seltxt"><span class="v">49</span><span class="vsp">&nbsp;</span>Nathanael answered him,</div> <div id="49b" class="txs seltxt">“<span class="glossary">Rabbi</span>,</div> <div id="49c" class="txs seltxt">you are the Son of God!</div> <div id="49d" class="txs seltxt">You are King of Israel!” </div><span id="bookmarks49"></span></div><span id="bookmarks49"></span>
    <div class="p"><div id="50a" class="txs seltxt"><span class="v">50</span><span class="vsp">&nbsp;</span><span class="glossary">Jesus</span> answered him,</div> <div id="50b" class="txs seltxt"><span class="wj">“Because I told you,</span></div> <div id="50c" class="txs seltxt"><span class="wj">‘I saw you underneath the fig tree,’</span></div> <div id="50d" class="txs seltxt"><span class="wj">do you believe?</span></div> <div id="50e" class="txs seltxt"><span class="wj">You will see greater things than these!”</span> </div><span id="bookmarks50"></span> <div id="51a" class="txs seltxt"><span class="v">51</span><span class="vsp">&nbsp;</span>He said to him,</div> <div id="51b" class="txs seltxt"><span class="wj">“Most certainly,</span></div> <div id="51c" class="txs seltxt"><span class="wj">I tell you all,</span></div> <div id="51d" class="txs seltxt"><span class="wj">hereafter you will see heaven opened,</span></div> <div id="51e" class="txs seltxt"><span class="wj">and the angels of God ascending and descending on the Son of Man.”</span> </div><span id="bookmarks51"></span></div>
</body>